### PR TITLE
Test with Node v4 in Travis

### PR DESCRIPTION
**Pull request by nexdrew**
And party like it's 1999.

### CODE REVIEW

**Comment by bcoe** [comment]
Can't believe Node V4 is here! looks great to me.

**Comment by nexdrew** [comment]
Had to fix some `xo` warnings in `test.js` as well. Squashed commits together to (hopefully) make @sindresorhus happy. :smiley:

@bcoe If the squashed commit looks good to you, I will merge.

**Comment by sindresorhus** [comment]
Remove `iojs` from the list. Otherwise lgtm.

**Comment by nexdrew** [comment]
@sindresorhus @bcoe Shall I publish a 1.5.0 release?

**Comment by sindresorhus** [comment]
Why? There's no new actual functionality.

**Comment by nexdrew** [comment]
True, but "officially works on Node v4"? I also just thought it was best practice to keep the current version in sync with master, unless further changes are anticipated soon.

**Comment by sindresorhus** [comment]
The currently published version also works on Node v4. I've never heard of that best practise tbh. Sounds like just waste of versions. I do publish often, but only when there are actual benefits.

**Comment by nexdrew** [comment]
Ok, got it.

**Pull request merged**
