### PR TITLE
Move opts to first argument of async method

### PR DESCRIPTION
**Pull request by nexdrew**
To match convention and the 1.3.0 readme doc. :smile:

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks for the quick fix :) Can you do a patch release?

**Comment by nexdrew** [comment]
No problem, will do. Thanks!

**Comment by nexdrew** [comment]
1.3.1 published. Thanks again, Sindre!

**Comment by bcoe** [comment]
\o/

**Pull request merged**
