### PR TITLE
Upgrade mem dependency

### PR DESCRIPTION
**Pull request by jeffal**
Hi @sindresorhus , upgrading as recommended by https://snyk.io/vuln/npm:mem:20180117

Thank you!

### CODE REVIEW

**Comment by spencern** [comment]
Came here to file an issue about this. 👍

**Comment by unsign3d** [comment]
I have the same problem with Snyk on some projects that I'm following

**Comment by jeffal** [comment]
@spencern The website url in your profile is missing a forward slash.

**Comment by spencern** [comment]
Thanks @jeffal. Fixed!

**Pull request merged**
