### PR TITLE
Use native execFileSync only (Node 0.11+)

### PR DESCRIPTION
**Pull request by nexdrew**
As suggested in [PR 10](https://github.com/sindresorhus/os-locale/pull/10#issuecomment-136675388), replace the `exec-file-sync` ponyfill to avoid problematic postinstall script from `spawn-sync` transitive dependency. This means the `sync()` method will only use environment variables for Node 0.10 or lower.

Successfully tested with:
- Node 0.10.40
- Node 0.11.16
- Node 0.12.7
- iojs 3.2.0

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you fix the merge conflict?

**Comment by nexdrew** [comment]
On it.

**Comment by nexdrew** [comment]
Done.

**Comment by bcoe** [comment]
@nexdrew awesome, this makes me really happy -- excited to nuke `locale.js` from yargs.

**Comment by nexdrew** [comment]
@sindresorhus @bcoe Ok to merge?

**Comment by sindresorhus** [comment]
Lgtm. Will do a new release tomorrow after some manual testing on various OSes. Thanks again :)

**Comment by nexdrew** [comment]
@sindresorhus Get a chance to test yet? Any way I can help?

**Comment by sindresorhus** [comment]
1.3.0 published.

**Comment by nexdrew** [comment]
@sindresorhus Awesome, thank you! :tada: :fireworks: :star2:

P.S. I like your readme content better than mine. :smiley:

**Comment by nexdrew** [comment]
Whoops, I added `opts` as the 2nd argument to `osLocale()`, but the readme says it is the 1st argument. Would you prefer that we change the code or change the readme?

**Comment by nexdrew** [comment]
PR #12 for the former option.

**Comment by sindresorhus** [comment]
Code

**Comment by sindresorhus** [comment]
Can you publish a new patch version when done? I'm afk.

**Comment by nexdrew** [comment]
Sure thing. Sorry for the mix-up!

**Comment by sindresorhus** [comment]
No worries. I'm the one that didn't notice.

**Pull request closed without merging**
