### PR TITLE
Upgrade `execa` to v4 and require Node.js 10

### PR DESCRIPTION
**Pull request by artursvonda**
Since Node v8 is being sunset at the end of the year, used this opportunity to jump on latest execa.

### CODE REVIEW

**Comment by sindresorhus** [comment]
I don’t personally like `execa.command`. I prefer the explicitly of an array of arguments. How is it easier to mock?

**Comment by artursvonda** [comment]
It was easier to mock property of execa instead of execa itself based on the code that already was there. I actually didn't try mocking execa.default to see if that would work. I think if we want mock the whole import (instead of just property like we do now), it requires different approach.
I'm open to suggests if you have any. When I have a moment to spare, I could also look into proper mocking of imports if you think the current solution will not work.

**Comment by sindresorhus** [comment]
> When I have a moment to spare, I could also look into proper mocking of imports if you think the current solution will not work.

Yes, I would prefer that. Could use `sinon` or `proxyquire`.

**Comment by artursvonda** [comment]
Rebased and now it's a lot cleaner.

**Comment by sindresorhus** [comment]
Great. Thanks :)

**Pull request merged**
